# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api.models.get_organization_quotas_usage_reply import GetOrganizationQuotasUsageReply

class TestGetOrganizationQuotasUsageReply(unittest.TestCase):
    """GetOrganizationQuotasUsageReply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOrganizationQuotasUsageReply:
        """Test GetOrganizationQuotasUsageReply
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOrganizationQuotasUsageReply`
        """
        model = GetOrganizationQuotasUsageReply()
        if include_optional:
            return GetOrganizationQuotasUsageReply(
                usage = koyeb.api.models.quota_usage.QuotaUsage(
                    apps_used = 56, 
                    apps_limit = 56, 
                    services_used = 56, 
                    services_limit = 56, 
                    memory_mb_used = 56, 
                    memory_mb_limit = 56, 
                    custom_domains_used = 56, 
                    custom_domains_limit = 56, 
                    koyeb_lb_domains_used = 56, 
                    koyeb_lb_domains_limit = 56, 
                    proxy_ports_used = 56, 
                    proxy_ports_limit = 56, 
                    instances_by_type = [
                        koyeb.api.models.instance_type_usage.InstanceTypeUsage(
                            instance_type = '', 
                            used = 56, 
                            limit = 56, )
                        ], 
                    persistent_volumes_by_region = [
                        koyeb.api.models.persistent_volume_region_usage.PersistentVolumeRegionUsage(
                            region = '', 
                            total_size_gb_used = 56, 
                            total_size_gb_limit = 56, )
                        ], 
                    instance_snapshots_by_type = [
                        koyeb.api.models.instance_snapshot_type_usage.InstanceSnapshotTypeUsage(
                            type = '', 
                            used = 56, 
                            limit = 56, )
                        ], )
            )
        else:
            return GetOrganizationQuotasUsageReply(
        )
        """

    def testGetOrganizationQuotasUsageReply(self):
        """Test GetOrganizationQuotasUsageReply"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
