# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api.models.create_project_reply import CreateProjectReply

class TestCreateProjectReply(unittest.TestCase):
    """CreateProjectReply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateProjectReply:
        """Test CreateProjectReply
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateProjectReply`
        """
        model = CreateProjectReply()
        if include_optional:
            return CreateProjectReply(
                project = koyeb.api.models.project.Project(
                    id = '', 
                    name = '', 
                    description = '', 
                    organization_id = '', 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    service_count = '', )
            )
        else:
            return CreateProjectReply(
        )
        """

    def testCreateProjectReply(self):
        """Test CreateProjectReply"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
