# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api.models.update_service_scaling_request import UpdateServiceScalingRequest

class TestUpdateServiceScalingRequest(unittest.TestCase):
    """UpdateServiceScalingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateServiceScalingRequest:
        """Test UpdateServiceScalingRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateServiceScalingRequest`
        """
        model = UpdateServiceScalingRequest()
        if include_optional:
            return UpdateServiceScalingRequest(
                scalings = [
                    koyeb.api.models.manual_service_scaling.ManualServiceScaling(
                        scopes = [
                            ''
                            ], 
                        instances = 56, )
                    ]
            )
        else:
            return UpdateServiceScalingRequest(
        )
        """

    def testUpdateServiceScalingRequest(self):
        """Test UpdateServiceScalingRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
