# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api.api.test_api import TestApi


class TestTestApi(unittest.IsolatedAsyncioTestCase):
    """TestApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = TestApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_test_anon(self) -> None:
        """Test case for test_anon

        Test anonymous call
        """
        pass

    async def test_test_auth(self) -> None:
        """Test case for test_auth

        Test authenticated call
        """
        pass


if __name__ == '__main__':
    unittest.main()
