# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api.models.get_pool_claim_reply import GetPoolClaimReply

class TestGetPoolClaimReply(unittest.TestCase):
    """GetPoolClaimReply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPoolClaimReply:
        """Test GetPoolClaimReply
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPoolClaimReply`
        """
        model = GetPoolClaimReply()
        if include_optional:
            return GetPoolClaimReply(
                claim = koyeb.api.models.pool_claim.PoolClaim(
                    id = '', 
                    pool_id = '', 
                    service_id = '', 
                    request_id = '', 
                    status = 'UNSPECIFIED', 
                    organization_id = '', 
                    workspace_id = '', 
                    customer_id = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    fulfilled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    released_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    pool_generation = '', )
            )
        else:
            return GetPoolClaimReply(
        )
        """

    def testGetPoolClaimReply(self):
        """Test GetPoolClaimReply"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
