# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api.models.list_projects_reply import ListProjectsReply

class TestListProjectsReply(unittest.TestCase):
    """ListProjectsReply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListProjectsReply:
        """Test ListProjectsReply
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListProjectsReply`
        """
        model = ListProjectsReply()
        if include_optional:
            return ListProjectsReply(
                projects = [
                    koyeb.api.models.project.Project(
                        id = '', 
                        name = '', 
                        description = '', 
                        organization_id = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        service_count = '', )
                    ],
                limit = 56,
                offset = 56
            )
        else:
            return ListProjectsReply(
        )
        """

    def testListProjectsReply(self):
        """Test ListProjectsReply"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
