# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api.api.service_pools_api import ServicePoolsApi


class TestServicePoolsApi(unittest.TestCase):
    """ServicePoolsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServicePoolsApi()

    def tearDown(self) -> None:
        pass

    def test_create_service_pool(self) -> None:
        """Test case for create_service_pool

        Create a ServicePool
        """
        pass

    def test_get_service_pool(self) -> None:
        """Test case for get_service_pool

        Get a ServicePool
        """
        pass

    def test_list_service_pools(self) -> None:
        """Test case for list_service_pools

        List ServicePools
        """
        pass


if __name__ == '__main__':
    unittest.main()
