# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MeshScope(str, Enum):
    """
    MeshScope selects which set of services can communicate over the mesh. Only meaningful when the mesh is on (i.e. DeploymentMesh is ENABLED, or AUTO and the service is eligible). UNSPECIFIED defers to the organization-level default (workspace-scoped since KOYEB-6062, legacy organizations opted back to organization scope via use_organization_level_mesh).   - MESH_SCOPE_ORGANIZATION: Private communication between services in the same organization (mesh label k-<orgId>).  - MESH_SCOPE_WORKSPACE: Private communication between services in the same workspace/project (mesh label pr_<projectId>).  - MESH_SCOPE_APP: Private communication between services in the same app (mesh label app_<appId>).  - MESH_SCOPE_CUSTOM: Private communication between services in the same workspace that share the same NetworkPolicy.mesh.name. Server-computed label is scoped by workspace, so the same custom name in different workspaces never collides.
    """

    """
    allowed enum values
    """
    MESH_SCOPE_UNSPECIFIED = 'MESH_SCOPE_UNSPECIFIED'
    MESH_SCOPE_ORGANIZATION = 'MESH_SCOPE_ORGANIZATION'
    MESH_SCOPE_WORKSPACE = 'MESH_SCOPE_WORKSPACE'
    MESH_SCOPE_APP = 'MESH_SCOPE_APP'
    MESH_SCOPE_CUSTOM = 'MESH_SCOPE_CUSTOM'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MeshScope from a JSON string"""
        return cls(json.loads(json_str))


