# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from koyeb.api_async.models.instance_snapshot_type_usage import InstanceSnapshotTypeUsage
from koyeb.api_async.models.instance_type_usage import InstanceTypeUsage
from koyeb.api_async.models.persistent_volume_region_usage import PersistentVolumeRegionUsage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class QuotaUsage(BaseModel):
    """
    QuotaUsage carries an organization's current resource consumption alongside the corresponding plan limits (from the caller's InternalToken.Quotas). Paused services are included in services_used but excluded from memory / instances_by_type / proxy_ports totals, matching enforcement semantics.
    """ # noqa: E501
    apps_used: Optional[StrictInt] = None
    apps_limit: Optional[StrictInt] = None
    services_used: Optional[StrictInt] = None
    services_limit: Optional[StrictInt] = None
    memory_mb_used: Optional[StrictInt] = None
    memory_mb_limit: Optional[StrictInt] = None
    custom_domains_used: Optional[StrictInt] = None
    custom_domains_limit: Optional[StrictInt] = None
    koyeb_lb_domains_used: Optional[StrictInt] = None
    koyeb_lb_domains_limit: Optional[StrictInt] = None
    proxy_ports_used: Optional[StrictInt] = None
    proxy_ports_limit: Optional[StrictInt] = None
    instances_by_type: Optional[List[InstanceTypeUsage]] = None
    persistent_volumes_by_region: Optional[List[PersistentVolumeRegionUsage]] = None
    instance_snapshots_by_type: Optional[List[InstanceSnapshotTypeUsage]] = None
    __properties: ClassVar[List[str]] = ["apps_used", "apps_limit", "services_used", "services_limit", "memory_mb_used", "memory_mb_limit", "custom_domains_used", "custom_domains_limit", "koyeb_lb_domains_used", "koyeb_lb_domains_limit", "proxy_ports_used", "proxy_ports_limit", "instances_by_type", "persistent_volumes_by_region", "instance_snapshots_by_type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QuotaUsage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in instances_by_type (list)
        _items = []
        if self.instances_by_type:
            for _item_instances_by_type in self.instances_by_type:
                if _item_instances_by_type:
                    _items.append(_item_instances_by_type.to_dict())
            _dict['instances_by_type'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in persistent_volumes_by_region (list)
        _items = []
        if self.persistent_volumes_by_region:
            for _item_persistent_volumes_by_region in self.persistent_volumes_by_region:
                if _item_persistent_volumes_by_region:
                    _items.append(_item_persistent_volumes_by_region.to_dict())
            _dict['persistent_volumes_by_region'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in instance_snapshots_by_type (list)
        _items = []
        if self.instance_snapshots_by_type:
            for _item_instance_snapshots_by_type in self.instance_snapshots_by_type:
                if _item_instance_snapshots_by_type:
                    _items.append(_item_instance_snapshots_by_type.to_dict())
            _dict['instance_snapshots_by_type'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QuotaUsage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apps_used": obj.get("apps_used"),
            "apps_limit": obj.get("apps_limit"),
            "services_used": obj.get("services_used"),
            "services_limit": obj.get("services_limit"),
            "memory_mb_used": obj.get("memory_mb_used"),
            "memory_mb_limit": obj.get("memory_mb_limit"),
            "custom_domains_used": obj.get("custom_domains_used"),
            "custom_domains_limit": obj.get("custom_domains_limit"),
            "koyeb_lb_domains_used": obj.get("koyeb_lb_domains_used"),
            "koyeb_lb_domains_limit": obj.get("koyeb_lb_domains_limit"),
            "proxy_ports_used": obj.get("proxy_ports_used"),
            "proxy_ports_limit": obj.get("proxy_ports_limit"),
            "instances_by_type": [InstanceTypeUsage.from_dict(_item) for _item in obj["instances_by_type"]] if obj.get("instances_by_type") is not None else None,
            "persistent_volumes_by_region": [PersistentVolumeRegionUsage.from_dict(_item) for _item in obj["persistent_volumes_by_region"]] if obj.get("persistent_volumes_by_region") is not None else None,
            "instance_snapshots_by_type": [InstanceSnapshotTypeUsage.from_dict(_item) for _item in obj["instance_snapshots_by_type"]] if obj.get("instance_snapshots_by_type") is not None else None
        })
        return _obj


