# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from koyeb.api.models.pool_claim_status import PoolClaimStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PoolClaim(BaseModel):
    """
    PoolClaim
    """ # noqa: E501
    id: Optional[StrictStr] = None
    pool_id: Optional[StrictStr] = None
    service_id: Optional[StrictStr] = None
    request_id: Optional[StrictStr] = None
    status: Optional[PoolClaimStatus] = PoolClaimStatus.UNSPECIFIED
    organization_id: Optional[StrictStr] = None
    workspace_id: Optional[StrictStr] = None
    customer_id: Optional[StrictStr] = None
    created_at: Optional[datetime] = None
    fulfilled_at: Optional[datetime] = None
    released_at: Optional[datetime] = None
    pool_generation: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "pool_id", "service_id", "request_id", "status", "organization_id", "workspace_id", "customer_id", "created_at", "fulfilled_at", "released_at", "pool_generation"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PoolClaim from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PoolClaim from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "pool_id": obj.get("pool_id"),
            "service_id": obj.get("service_id"),
            "request_id": obj.get("request_id"),
            "status": obj.get("status") if obj.get("status") is not None else PoolClaimStatus.UNSPECIFIED,
            "organization_id": obj.get("organization_id"),
            "workspace_id": obj.get("workspace_id"),
            "customer_id": obj.get("customer_id"),
            "created_at": obj.get("created_at"),
            "fulfilled_at": obj.get("fulfilled_at"),
            "released_at": obj.get("released_at"),
            "pool_generation": obj.get("pool_generation")
        })
        return _obj


