# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.quotas_api import QuotasApi


class TestQuotasApi(unittest.IsolatedAsyncioTestCase):
    """QuotasApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = QuotasApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_review_organization_capacity(self) -> None:
        """Test case for review_organization_capacity

        DEPRECATED: Review Organization Capacity
        """
        pass


if __name__ == '__main__':
    unittest.main()
