# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.services_api import ServicesApi


class TestServicesApi(unittest.IsolatedAsyncioTestCase):
    """ServicesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ServicesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_autocomplete(self) -> None:
        """Test case for autocomplete

        Autocomplete definition
        """
        pass

    async def test_create_service(self) -> None:
        """Test case for create_service

        Create Service
        """
        pass

    async def test_delete_service(self) -> None:
        """Test case for delete_service

        Delete Service
        """
        pass

    async def test_delete_service_scaling(self) -> None:
        """Test case for delete_service_scaling

        Delete Service Scaling
        """
        pass

    async def test_get_service(self) -> None:
        """Test case for get_service

        Get Service
        """
        pass

    async def test_get_service_scaling(self) -> None:
        """Test case for get_service_scaling

        Get Service Scaling
        """
        pass

    async def test_list_service_events(self) -> None:
        """Test case for list_service_events

        List Service events
        """
        pass

    async def test_list_services(self) -> None:
        """Test case for list_services

        List Services
        """
        pass

    async def test_pause_service(self) -> None:
        """Test case for pause_service

        Pause Service
        """
        pass

    async def test_re_deploy(self) -> None:
        """Test case for re_deploy

        ReDeploy Service
        """
        pass

    async def test_resume_service(self) -> None:
        """Test case for resume_service

        Resume Service
        """
        pass

    async def test_update_service(self) -> None:
        """Test case for update_service

        Update Service
        """
        pass

    async def test_update_service2(self) -> None:
        """Test case for update_service2

        Update Service
        """
        pass

    async def test_update_service_scaling(self) -> None:
        """Test case for update_service_scaling

        Update Service Scaling
        """
        pass


if __name__ == '__main__':
    unittest.main()
