# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.instances_api import InstancesApi


class TestInstancesApi(unittest.IsolatedAsyncioTestCase):
    """InstancesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = InstancesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_exec_command(self) -> None:
        """Test case for exec_command

        Exec Command
        """
        pass

    async def test_get_instance(self) -> None:
        """Test case for get_instance

        Get Instance
        """
        pass

    async def test_list_instance_events(self) -> None:
        """Test case for list_instance_events

        List Instance events
        """
        pass

    async def test_list_instances(self) -> None:
        """Test case for list_instances

        List Instances
        """
        pass


if __name__ == '__main__':
    unittest.main()
