# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.provisioning_api import ProvisioningApi


class TestProvisioningApi(unittest.IsolatedAsyncioTestCase):
    """ProvisioningApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ProvisioningApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_stage_attempt(self) -> None:
        """Test case for create_stage_attempt

        Create an attempt for a stage
        """
        pass

    async def test_declare_stage_progress(self) -> None:
        """Test case for declare_stage_progress

        Declare stage progress
        """
        pass

    async def test_declare_step_progress(self) -> None:
        """Test case for declare_step_progress

        Declare step progress
        """
        pass


if __name__ == '__main__':
    unittest.main()
