# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.intercom_api import IntercomApi


class TestIntercomApi(unittest.IsolatedAsyncioTestCase):
    """IntercomApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = IntercomApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_intercom_profile(self) -> None:
        """Test case for get_intercom_profile

        Get intercom profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
