# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.catalog_datacenters_api import CatalogDatacentersApi


class TestCatalogDatacentersApi(unittest.IsolatedAsyncioTestCase):
    """CatalogDatacentersApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = CatalogDatacentersApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_list_datacenters(self) -> None:
        """Test case for list_datacenters

        List datacenters
        """
        pass


if __name__ == '__main__':
    unittest.main()
