# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.invite_api import InviteApi


class TestInviteApi(unittest.IsolatedAsyncioTestCase):
    """InviteApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = InviteApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_invite(self) -> None:
        """Test case for create_invite

        DEPRECATED: this has been replaced by WorkOS and will be dropped soon.
        """
        pass


if __name__ == '__main__':
    unittest.main()
