# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.regional_deployments_api import RegionalDeploymentsApi


class TestRegionalDeploymentsApi(unittest.IsolatedAsyncioTestCase):
    """RegionalDeploymentsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = RegionalDeploymentsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_regional_deployment(self) -> None:
        """Test case for get_regional_deployment

        Get Regional Deployment
        """
        pass

    async def test_list_regional_deployment_events(self) -> None:
        """Test case for list_regional_deployment_events

        List Regional Deployment events
        """
        pass

    async def test_list_regional_deployments(self) -> None:
        """Test case for list_regional_deployments

        List Regional Deployments
        """
        pass


if __name__ == '__main__':
    unittest.main()
