# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.logs_api import LogsApi


class TestLogsApi(unittest.IsolatedAsyncioTestCase):
    """LogsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = LogsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_query_logs(self) -> None:
        """Test case for query_logs

        Query logs
        """
        pass

    async def test_tail_logs(self) -> None:
        """Test case for tail_logs

        Tails logs
        """
        pass


if __name__ == '__main__':
    unittest.main()
