# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.secrets_api import SecretsApi


class TestSecretsApi(unittest.IsolatedAsyncioTestCase):
    """SecretsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SecretsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_secret(self) -> None:
        """Test case for create_secret

        Create Secret
        """
        pass

    async def test_delete_secret(self) -> None:
        """Test case for delete_secret

        Delete Secret
        """
        pass

    async def test_get_secret(self) -> None:
        """Test case for get_secret

        Get Secret
        """
        pass

    async def test_list_secrets(self) -> None:
        """Test case for list_secrets

        List Secrets
        """
        pass

    async def test_reveal_secret(self) -> None:
        """Test case for reveal_secret

        Reveal Secret
        """
        pass

    async def test_update_secret(self) -> None:
        """Test case for update_secret

        Update Secret
        """
        pass

    async def test_update_secret2(self) -> None:
        """Test case for update_secret2

        Update Secret
        """
        pass


if __name__ == '__main__':
    unittest.main()
