# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.activity_api import ActivityApi


class TestActivityApi(unittest.IsolatedAsyncioTestCase):
    """ActivityApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ActivityApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_account_activities(self) -> None:
        """Test case for get_account_activities

        """
        pass

    async def test_list_activities(self) -> None:
        """Test case for list_activities

        List Activities
        """
        pass

    async def test_list_notifications(self) -> None:
        """Test case for list_notifications

        List Notifications
        """
        pass


if __name__ == '__main__':
    unittest.main()
