# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.credentials_api import CredentialsApi


class TestCredentialsApi(unittest.IsolatedAsyncioTestCase):
    """CredentialsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = CredentialsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_credential(self) -> None:
        """Test case for create_credential

        Create credential
        """
        pass

    async def test_delete_credential(self) -> None:
        """Test case for delete_credential

        Delete credential
        """
        pass

    async def test_get_credential(self) -> None:
        """Test case for get_credential

        Get credential
        """
        pass

    async def test_list_credentials(self) -> None:
        """Test case for list_credentials

        List credentials
        """
        pass

    async def test_update_credential(self) -> None:
        """Test case for update_credential

        Update credential
        """
        pass

    async def test_update_credential2(self) -> None:
        """Test case for update_credential2

        Update credential
        """
        pass


if __name__ == '__main__':
    unittest.main()
