# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.repositories_api import RepositoriesApi


class TestRepositoriesApi(unittest.IsolatedAsyncioTestCase):
    """RepositoriesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = RepositoriesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_list_branches(self) -> None:
        """Test case for list_branches

        List Branches
        """
        pass

    async def test_list_repositories(self) -> None:
        """Test case for list_repositories

        List Repositories
        """
        pass

    async def test_resync_organization(self) -> None:
        """Test case for resync_organization

        Resync Organization
        """
        pass


if __name__ == '__main__':
    unittest.main()
