# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.payment_methods_api import PaymentMethodsApi


class TestPaymentMethodsApi(unittest.IsolatedAsyncioTestCase):
    """PaymentMethodsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = PaymentMethodsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_confirm_payment_authorization(self) -> None:
        """Test case for confirm_payment_authorization

        Confirm payment authorization
        """
        pass

    async def test_create_payment_authorization(self) -> None:
        """Test case for create_payment_authorization

        Create payment authorization
        """
        pass

    async def test_delete_payment_method(self) -> None:
        """Test case for delete_payment_method

        Delete payment method
        """
        pass

    async def test_get_payment_method(self) -> None:
        """Test case for get_payment_method

        Get payment method
        """
        pass

    async def test_list_payment_methods(self) -> None:
        """Test case for list_payment_methods

        List payment methods
        """
        pass


if __name__ == '__main__':
    unittest.main()
