# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.organization_api import OrganizationApi


class TestOrganizationApi(unittest.IsolatedAsyncioTestCase):
    """OrganizationApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = OrganizationApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_access_token(self) -> None:
        """Test case for create_access_token

        CreateAccessToken
        """
        pass

    async def test_create_budget(self) -> None:
        """Test case for create_budget

        Create Budget
        """
        pass

    async def test_create_organization(self) -> None:
        """Test case for create_organization

        Create Organization
        """
        pass

    async def test_deactivate_organization(self) -> None:
        """Test case for deactivate_organization

        Deactivate an Organization
        """
        pass

    async def test_delete_budget(self) -> None:
        """Test case for delete_budget

        Delete Budget
        """
        pass

    async def test_delete_organization(self) -> None:
        """Test case for delete_organization

        Delete an Organization
        """
        pass

    async def test_get_budget(self) -> None:
        """Test case for get_budget

        Get Budget
        """
        pass

    async def test_get_github_installation(self) -> None:
        """Test case for get_github_installation

        Fetch Github Installation configuration
        """
        pass

    async def test_get_organization(self) -> None:
        """Test case for get_organization

        Get Organization
        """
        pass

    async def test_github_installation(self) -> None:
        """Test case for github_installation

        Start Github Installation
        """
        pass

    async def test_reactivate_organization(self) -> None:
        """Test case for reactivate_organization

        Reactivate an Organization
        """
        pass

    async def test_switch_organization(self) -> None:
        """Test case for switch_organization

        Switch Organization context DEPRECATED: this has been replaced by WorkOS and will be dropped soon.
        """
        pass

    async def test_unscope_organization_token(self) -> None:
        """Test case for unscope_organization_token

        Unscope Organization Token
        """
        pass

    async def test_update_budget(self) -> None:
        """Test case for update_budget

        Update Budget
        """
        pass

    async def test_update_organization(self) -> None:
        """Test case for update_organization

        Update Organization
        """
        pass

    async def test_update_organization2(self) -> None:
        """Test case for update_organization2

        Update Organization
        """
        pass

    async def test_update_organization_default_project(self) -> None:
        """Test case for update_organization_default_project

        Update Organization's default project
        """
        pass

    async def test_update_organization_name(self) -> None:
        """Test case for update_organization_name

        Update Organization Name
        """
        pass

    async def test_update_organization_plan(self) -> None:
        """Test case for update_organization_plan

        Update Organization plan
        """
        pass

    async def test_upsert_signup_qualification(self) -> None:
        """Test case for upsert_signup_qualification

        Upsert Organization's signup qualification
        """
        pass


if __name__ == '__main__':
    unittest.main()
