# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.usages_api import UsagesApi


class TestUsagesApi(unittest.IsolatedAsyncioTestCase):
    """UsagesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = UsagesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_organization_usage(self) -> None:
        """Test case for get_organization_usage

        Get organization usage
        """
        pass

    async def test_get_organization_usage_details(self) -> None:
        """Test case for get_organization_usage_details

        Get organization usage details
        """
        pass


if __name__ == '__main__':
    unittest.main()
