# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.pool_claims_api import PoolClaimsApi


class TestPoolClaimsApi(unittest.IsolatedAsyncioTestCase):
    """PoolClaimsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = PoolClaimsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_claim(self) -> None:
        """Test case for claim

        Claim a sandbox from a service pool
        """
        pass

    async def test_get_claim(self) -> None:
        """Test case for get_claim

        Get a claim
        """
        pass

    async def test_list_claim(self) -> None:
        """Test case for list_claim

        List claims of a service pool
        """
        pass


if __name__ == '__main__':
    unittest.main()
