# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.snapshots_api import SnapshotsApi


class TestSnapshotsApi(unittest.IsolatedAsyncioTestCase):
    """SnapshotsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SnapshotsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_snapshot(self) -> None:
        """Test case for create_snapshot

        Create a Snapshot
        """
        pass

    async def test_delete_snapshot(self) -> None:
        """Test case for delete_snapshot

        Delete a Snapshot
        """
        pass

    async def test_get_snapshot(self) -> None:
        """Test case for get_snapshot

        Get a Snapshot
        """
        pass

    async def test_list_snapshots(self) -> None:
        """Test case for list_snapshots

        List all Snapshots
        """
        pass

    async def test_update_snapshot(self) -> None:
        """Test case for update_snapshot

        Update a Snapshot
        """
        pass


if __name__ == '__main__':
    unittest.main()
