# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.organization_invitations_api import OrganizationInvitationsApi


class TestOrganizationInvitationsApi(unittest.IsolatedAsyncioTestCase):
    """OrganizationInvitationsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = OrganizationInvitationsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_organization_invitation(self) -> None:
        """Test case for create_organization_invitation

        Create Organization Invitation
        """
        pass

    async def test_delete_organization_invitation(self) -> None:
        """Test case for delete_organization_invitation

        Delete Organization Invitation
        """
        pass

    async def test_get_organization_invitation(self) -> None:
        """Test case for get_organization_invitation

        Get Organization Invitation
        """
        pass

    async def test_list_organization_invitations(self) -> None:
        """Test case for list_organization_invitations

        List Organization Invitations
        """
        pass

    async def test_resend_organization_invitation(self) -> None:
        """Test case for resend_organization_invitation

        Resend Organization Invitation
        """
        pass


if __name__ == '__main__':
    unittest.main()
