# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.IsolatedAsyncioTestCase):
    """ProjectsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ProjectsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_project(self) -> None:
        """Test case for create_project

        Create project
        """
        pass

    async def test_delete_project(self) -> None:
        """Test case for delete_project

        Delete project
        """
        pass

    async def test_get_project(self) -> None:
        """Test case for get_project

        Get project
        """
        pass

    async def test_list_projects(self) -> None:
        """Test case for list_projects

        List projects
        """
        pass

    async def test_update_project(self) -> None:
        """Test case for update_project

        Update project
        """
        pass

    async def test_update_project2(self) -> None:
        """Test case for update_project2

        Update project
        """
        pass


if __name__ == '__main__':
    unittest.main()
