# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.models.autocomplete_request import AutocompleteRequest

class TestAutocompleteRequest(unittest.TestCase):
    """AutocompleteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutocompleteRequest:
        """Test AutocompleteRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutocompleteRequest`
        """
        model = AutocompleteRequest()
        if include_optional:
            return AutocompleteRequest(
                definition = koyeb.api_async.models.deployment_definition.DeploymentDefinition(
                    name = '', 
                    type = 'INVALID', 
                    strategy = koyeb.api_async.models.deployment_strategy.DeploymentStrategy(), 
                    routes = [
                        koyeb.api_async.models.deployment_route.DeploymentRoute(
                            port = 56, 
                            path = '', 
                            security_policies = koyeb.api_async.models.security_policies.SecurityPolicies(
                                basic_auths = [
                                    koyeb.api_async.models.basic_auth_policy.BasicAuthPolicy(
                                        username = '', 
                                        password = '', )
                                    ], 
                                api_keys = [
                                    ''
                                    ], ), )
                        ], 
                    ports = [
                        koyeb.api_async.models.deployment_port.DeploymentPort(
                            port = 56, 
                            protocol = '', )
                        ], 
                    proxy_ports = [
                        koyeb.api_async.models.deployment_proxy_port.DeploymentProxyPort(
                            port = 56, 
                            protocol = 'tcp', )
                        ], 
                    env = [
                        koyeb.api_async.models.deployment_env.DeploymentEnv(
                            scopes = [
                                ''
                                ], 
                            key = '', 
                            value = '', 
                            secret = '', )
                        ], 
                    regions = [
                        ''
                        ], 
                    scalings = [
                        koyeb.api_async.models.deployment_scaling.DeploymentScaling(
                            min = 56, 
                            max = 56, 
                            targets = [
                                koyeb.api_async.models.deployment_scaling_target.DeploymentScalingTarget(
                                    average_cpu = koyeb.api_async.models.deployment_scaling_target_average_cpu.DeploymentScalingTargetAverageCPU(
                                        value = 56, ), 
                                    average_mem = koyeb.api_async.models.deployment_scaling_target_average_mem.DeploymentScalingTargetAverageMem(
                                        value = 56, ), 
                                    requests_per_second = koyeb.api_async.models.deployment_scaling_target_requests_per_second.DeploymentScalingTargetRequestsPerSecond(
                                        value = 56, ), 
                                    concurrent_requests = koyeb.api_async.models.deployment_scaling_target_concurrent_requests.DeploymentScalingTargetConcurrentRequests(
                                        value = 56, ), 
                                    requests_response_time = koyeb.api_async.models.deployment_scaling_target_requests_response_time.DeploymentScalingTargetRequestsResponseTime(
                                        value = 56, 
                                        quantile = 56, ), 
                                    sleep_idle_delay = koyeb.api_async.models.deployment_scaling_target_sleep_idle_delay.DeploymentScalingTargetSleepIdleDelay(
                                        value = 56, 
                                        deep_sleep_value = 56, 
                                        light_sleep_value = 56, ), )
                                ], )
                        ], 
                    instance_types = [
                        koyeb.api_async.models.deployment_instance_type.DeploymentInstanceType()
                        ], 
                    health_checks = [
                        koyeb.api_async.models.deployment_health_check.DeploymentHealthCheck(
                            grace_period = 56, 
                            interval = 56, 
                            restart_limit = 56, 
                            timeout = 56, 
                            tcp = koyeb.api_async.models.tcp_health_check.TCPHealthCheck(
                                port = 56, ), 
                            http = koyeb.api_async.models.http_health_check.HTTPHealthCheck(
                                port = 56, 
                                path = '', 
                                method = '', 
                                headers = [
                                    koyeb.api_async.models.http_header.HTTPHeader(
                                        key = '', 
                                        value = '', )
                                    ], ), )
                        ], 
                    volumes = [
                        koyeb.api_async.models.deployment_volume.DeploymentVolume(
                            id = '', 
                            path = '', 
                            replica_index = 56, )
                        ], 
                    config_files = [
                        koyeb.api_async.models.config_file.ConfigFile(
                            path = '', 
                            permissions = '', 
                            content = '', )
                        ], 
                    skip_cache = True, 
                    mesh = 'DEPLOYMENT_MESH_AUTO', 
                    docker = koyeb.api_async.models.docker_source.DockerSource(
                        image = '', 
                        command = '', 
                        args = [
                            ''
                            ], 
                        image_registry_secret = '', 
                        entrypoint = [
                            ''
                            ], 
                        privileged = True, ), 
                    git = koyeb.api_async.models.git_source.GitSource(
                        repository = '', 
                        branch = '', 
                        tag = '', 
                        sha = '', 
                        build_command = '', 
                        run_command = '', 
                        no_deploy_on_push = True, 
                        workdir = '', 
                        buildpack = koyeb.api_async.models.buildpack_builder.BuildpackBuilder(
                            build_command = '', 
                            run_command = '', 
                            privileged = True, ), ), 
                    database = koyeb.api_async.models.database_source.DatabaseSource(
                        neon_postgres = koyeb.api_async.models.neon_postgres_database.NeonPostgresDatabase(
                            pg_version = 56, 
                            region = '', 
                            instance_type = '', 
                            roles = [
                                koyeb.api_async.models.neon_postgres_database/neon_role.NeonPostgresDatabase.NeonRole(
                                    name = '', 
                                    secret = '', )
                                ], 
                            databases = [
                                koyeb.api_async.models.neon_postgres_database/neon_database.NeonPostgresDatabase.NeonDatabase(
                                    name = '', 
                                    owner = '', )
                                ], ), ), 
                    archive = koyeb.api_async.models.archive_source.ArchiveSource(
                        id = '', ), )
            )
        else:
            return AutocompleteRequest(
        )
        """

    def testAutocompleteRequest(self):
        """Test AutocompleteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
