# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.coupons_api import CouponsApi


class TestCouponsApi(unittest.IsolatedAsyncioTestCase):
    """CouponsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = CouponsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_check_coupon(self) -> None:
        """Test case for check_coupon

        Check Coupon
        """
        pass

    async def test_redeem_coupon(self) -> None:
        """Test case for redeem_coupon

        Redeem Coupon
        """
        pass


if __name__ == '__main__':
    unittest.main()
