# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.api.sessions_api import SessionsApi


class TestSessionsApi(unittest.IsolatedAsyncioTestCase):
    """SessionsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SessionsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_login(self) -> None:
        """Test case for login

        Login user DEPRECATED: this has been replaced by WorkOS and will be dropped soon.
        """
        pass

    async def test_logout(self) -> None:
        """Test case for logout

        Logout user DEPRECATED: this has been replaced by WorkOS and will be dropped soon.
        """
        pass

    async def test_new_session(self) -> None:
        """Test case for new_session

        New session
        """
        pass

    async def test_refresh_token(self) -> None:
        """Test case for refresh_token

        Refresh token DEPRECATED: this has been replaced by WorkOS and will be dropped soon.
        """
        pass


if __name__ == '__main__':
    unittest.main()
